version: '3.9'

services:
  minecraft_vanilla_1_20_1:
    build: ./1.20.1
    ports: 
      - '25565:25565'
    volumes: 
      - './1.20.1/.map/world:/minecraft-server/world'
      - './1.20.1/.map/world_nether:/minecraft-server/world_nether'
      - './1.20.1/.map/world_the_end:/minecraft-server/world_the_end'