version: '3.9'

networks:
  # Internal private servers network
  private:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/29

  # Internal LavaLawsLess public server network
  public_1:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/30

# Minecraft Servers
services:

# Private Test Spigot server
  test_spigot_1_20_1:
    build: ./1.20.1/private/spigot
    volumes:
      - './1.20.1/private/spigot/.map/world:/spigot-server/world'
      - './1.20.1/private/spigot/.map/world_nether:/spigot-server/world_nether'
      - './1.20.1/private/spigot/.map/world_the_end:/spigot-server/world_the_end'
      - './1.20.1/private/spigot/.properties/whitelist.json:/spigot-server/whitelist.json'
      #- './1.20.1/private/spigot/.properties/blacklist.json:/spigot-server/blacklist.json'
      #- './1.20.1/private/spigot/.properties/ops.json:/spigot-server/ops.json'
    networks:
      - private
    ports:
      - "25567:25566"
    stdin_open: true
    tty: true

# Public Spigot API server
  lavalawless_spigot_1_20_1:
    build: 1.20.1/public/anarchy.lavalawsless.com
    volumes:
      - './1.20.1/public/anarchy.lavalawless.com/.map/world:/spigot-server/world'
      - './1.20.1/public/anarchy.lavalawless.com/.map/world_nether:/spigot-server/world_nether'
      - './1.20.1/public/anarchy.lavalawless.com/.map/world_the_end:/spigot-server/world_the_end'
      #- './1.20.1/public/anarchy.lavalawless.com/.properties/blacklist.json:/spigot-server/blacklist.json'
      #- './1.20.1/public/anarchy.lavalawless.com/.properties/ops.json:/spigot-server/ops.json'
    networks:
      - public_1
    ports:
      - "25565:25565"
    stdin_open: true
    tty: true