version: '3.9'

networks:
  # Minecraft Servers router network
  proxy_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/29

  # Internal private servers network
  private:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/29

  # Internal LavaLawsLess public server network
  public_1:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/30

# Minecraft Servers
services:
  # Minecraft Servers router
  traefik_servers_proxy:
    image: "traefik:v2.5"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "9190:80"
      - "9191:8080" # The Web UI (enabled by --api.insecure=true)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.toml:/etc/traefik/traefik.toml"
    networks:
      proxy_network:
        ipv4_address: 192.168.1.2

  # Private vanilla server
  minecraft_vanilla_1_20_1:
    build: ./1.20.1/private/vanilla
    volumes: 
      - './1.20.1/private/vanilla/.map/world:/minecraft-server/world'
      - './1.20.1/private/vanilla/.map/world_nether:/minecraft-server/world_nether'
      - './1.20.1/private/vanilla/.map/world_the_end:/minecraft-server/world_the_end'
      - './1.20.1/private/vanilla/whitelist.json:/minecraft-server/whitelist.json'
    networks:
      private:
        ipv4_address: 172.16.0.2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lavalawless.rule=Host(`minecraft.vanilla.lkh.coffee`)"
      - "traefik.http.services.lavalawless.loadbalancer.server.port=25565"

  # Private Test Spigot server
  minecraft_spygot_1_20_1:
    build: ./1.20.1/private/spigot
    volumes:
      - './1.20.1/spigot/private/.map/world:/minecraft-server/world'
      - './1.20.1/spigot/private/.map/world_nether:/minecraft-server/world_nether'
      - './1.20.1/spigot/private/.map/world_the_end:/minecraft-server/world_the_end'
    networks:
      private:
        ipv4_address: 172.16.0.3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lavalawless.rule=Host(`minecraft.spigot.lkh.coffee`)"
      - "traefik.http.services.lavalawless.loadbalancer.server.port=25566"

# Public Spigot API server
  lavalawless_vanilla_1_20_1:
    build: 1.20.1/public/anarchy.lavalawsless.com
    volumes:
      - './1.20.1/public/anarchy.lavalawless.com/.map/world:/minecraft-server/world'
      - './1.20.1/public/anarchy.lavalawless.com/.map/world_nether:/minecraft-server/world_nether'
      - './1.20.1/public/anarchy.lavalawless.com/.map/world_the_end:/minecraft-server/world_the_end'
      - './1.20.1/public/anarchy.lavalawless.com/blacklist.json:/minecraft-server/blacklist.json'
    networks:
      public_1:
        ipv4_address: 192.168.0.2

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lavalawless.rule=Host(`anarchy.lavalawsless.com`)"
      - "traefik.http.services.lavalawless.loadbalancer.server.port=25567"