name: Docker Image CI

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Compose servers images
      run: mkdir -p ./1.20.1/.map/world | mkdir -p ./1.20.1/.map/world_nether | mkdir -p ./1.20.1/.map/world_the_end | docker compose -p minecraft-servers up -d
